### ISSUE TITLE
Сведения о состоянии юридического лица

### ISSUE THREAD

**Issue by ghost** [antonshell/egrul-nalog-parser#1]
Некорректно парсится раздел "Сведения о состоянии юридического лица", например ИНН 7810531436

**Comment by antonshell** [comment]
Проверил, не хватало описания части полей в парсере. 
Пример документа:
[ul-1089847376189-20190214161429.pdf](https://github.com/antonshell/egrul-nalog-parser/files/2868787/ul-1089847376189-20190214161429.pdf)

Исправил:
https://github.com/antonshell/egrul-nalog-parser/commit/be881c996276c71af4fd384473f46e22f28146ba

Сделал релиз 0.0.6

Проверить можно здесь:
http://demo.antonshell.me/egrul-nalog-parser/
